import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Gerrard Butarbutar - 31200008
 */
public class frmCetakReport extends javax.swing.JFrame {
    clsCetakReport objCetakReport = new clsCetakReport();
    /**
     * Creates new form frmCetakReport
     */
    public frmCetakReport() {
        initComponents();
        IsicboId1();
        IsicboId2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboId1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboId2 = new javax.swing.JComboBox<>();
        btnCetak = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        menuKue = new javax.swing.JMenuItem();
        menuPembeli = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCetakReport = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Toko Kue");

        jLabel2.setText("Cetak Transaksi Dari");

        cboId1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Sampai");

        cboId2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel4.setText("© Gerrard Butarbutar - 2021/2022");

        jMenu1.setText("File");

        jMenu2.setText("Master");

        menuUser.setText("User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        jMenu2.add(menuUser);

        menuKue.setText("Kue");
        menuKue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKueActionPerformed(evt);
            }
        });
        jMenu2.add(menuKue);

        menuPembeli.setText("Pembeli");
        menuPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembeliActionPerformed(evt);
            }
        });
        jMenu2.add(menuPembeli);

        jMenu1.add(jMenu2);

        menuTransaksi.setText("Transaksi");
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });
        jMenu1.add(menuTransaksi);

        jMenu4.setText("Report");

        menuCetakReport.setText("Cetak Report");
        menuCetakReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCetakReportActionPerformed(evt);
            }
        });
        jMenu4.add(menuCetakReport);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Log Out");

        menuLogout.setText("Log Out");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu3.add(menuLogout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCetak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(btnMenu))
                            .addComponent(jLabel2)
                            .addComponent(cboId1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(cboId2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak)
                    .addComponent(btnMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void IsicboId1(){
        try{
            cboId1.removeAllItems();
            objCetakReport.AksesData();
            String sql1 = "select id_transaksi from tbltransaksi";
            Statement stat1 = objCetakReport.conn.createStatement();
            ResultSet res1=stat1.executeQuery(sql1);
            cboId1.addItem("Pilih ID Transaksi");
            while(res1.next()){
                cboId1.addItem(res1.getString("id_transaksi"));
            }
        }
        catch(Exception e){
        }
    }
    
    public void IsicboId2(){
        try{
            cboId2.removeAllItems();
            objCetakReport.AksesData();
            String sql1 = "select id_transaksi from tbltransaksi";
            Statement stat1 = objCetakReport.conn.createStatement();
            ResultSet res1=stat1.executeQuery(sql1);
            cboId2.addItem("Pilih ID Transaksi");
            while(res1.next()){
                cboId2.addItem(res1.getString("Id_transaksi"));
            }
        }
        catch(Exception e){
        }
    }
    
    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
        frmUser user = new frmUser();
        dispose();
        user.show();
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuKueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKueActionPerformed
        // TODO add your handling code here:
        frmKue kue = new frmKue();
        dispose();
        kue.show();
    }//GEN-LAST:event_menuKueActionPerformed

    private void menuPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembeliActionPerformed
        // TODO add your handling code here:
        frmPembeli pembeli = new frmPembeli();
        dispose();
        pembeli.show();
    }//GEN-LAST:event_menuPembeliActionPerformed

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed
        // TODO add your handling code here:
        frmTransaksi transaksi = new frmTransaksi();
        dispose();
        transaksi.show();
    }//GEN-LAST:event_menuTransaksiActionPerformed

    private void menuCetakReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCetakReportActionPerformed
        // TODO add your handling code here:
        frmCetakReport report = new frmCetakReport();
        dispose();
        report.show();
    }//GEN-LAST:event_menuCetakReportActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sampai Jumpa, Semoga Hari Anda Menyenangkan :)");
        frmLogin login = new frmLogin();
        dispose();
        login.show();
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        frmMenu menu = new frmMenu();
        dispose();
        menu.show();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        JasperReport jasRep;
        JasperPrint jasPri;
        Map < String, Object> Idtransaksi = new HashMap<>();
        JasperDesign jasDes;
        try{
            objCetakReport.AksesData();
            File report1 = new File("../src/rptTransaksi.jrxml");
            jasDes = JRXmlLoader.load(report1);
            Idtransaksi.clear();
            objCetakReport.Kode1 = cboId1.getSelectedItem().toString().substring(0,4);
            objCetakReport.Kode2 = cboId2.getSelectedItem().toString().substring(0,4);
            Idtransaksi.put("mIdtransaksi", objCetakReport.Kode1);
            Idtransaksi.put("nIdtransaksi", objCetakReport.Kode2);
            jasRep = JasperCompileManager.compileReport(jasDes);
            jasPri = JasperFillManager.fillReport(jasRep, Idtransaksi, objCetakReport.conn);
            JasperViewer.viewReport(jasPri, false);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension posisi=Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width-this.getWidth())/2;
        int y = (posisi.height-this.getHeight())/2;
        this.setLocation(x,y);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCetakReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCetakReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCetakReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCetakReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCetakReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> cboId1;
    private javax.swing.JComboBox<String> cboId2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCetakReport;
    private javax.swing.JMenuItem menuKue;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPembeli;
    private javax.swing.JMenuItem menuTransaksi;
    private javax.swing.JMenuItem menuUser;
    // End of variables declaration//GEN-END:variables
}