import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Gerrard Butarbutar - 31200008
 */
public class frmKue extends javax.swing.JFrame {
    clsKue objKue = new clsKue();
    private TableColumn column;
    /**
     * Creates new form frmKue
     */
    public frmKue() {
        initComponents();
        objKue.AksesData();
        IsiTabel();
        AutoId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdkue = new javax.swing.JTextField();
        txtNamakue = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        menuKue = new javax.swing.JMenuItem();
        menuPembeli = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCetakReport = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Toko Kue");

        jLabel2.setText("ID Kue");

        jLabel3.setText("Nama Kue");

        jLabel5.setText("Harga");

        txtIdkue.setEnabled(false);
        txtIdkue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdkueKeyPressed(evt);
            }
        });

        txtNamakue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamakueKeyPressed(evt);
            }
        });

        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHargaKeyPressed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel6.setText("Data Master Kue");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel7.setText("©Gerrard Butarbutar - 2021/2022");

        jMenu1.setText("File");

        jMenu2.setText("Master");

        menuUser.setText("User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        jMenu2.add(menuUser);

        menuKue.setText("Kue");
        menuKue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKueActionPerformed(evt);
            }
        });
        jMenu2.add(menuKue);

        menuPembeli.setText("Pembeli");
        menuPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembeliActionPerformed(evt);
            }
        });
        jMenu2.add(menuPembeli);

        jMenu1.add(jMenu2);

        menuTransaksi.setText("Transaksi");
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });
        jMenu1.add(menuTransaksi);

        jMenu4.setText("Report");

        menuCetakReport.setText("Cetak Report");
        menuCetakReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCetakReportActionPerformed(evt);
            }
        });
        jMenu4.add(menuCetakReport);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Log Out");

        menuLogout.setText("Log Out");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu3.add(menuLogout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(238, 238, 238))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(txtIdkue, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(txtNamakue)
                            .addComponent(txtHarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(346, 346, 346))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdkue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamakue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnMenu))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void AutoId(){
        try{
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbtokokue","root","");
            Statement stat = koneksi.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM tblkue order by id_kue desc");
            if (rs.next()){
                String kode = rs.getString("id_kue").substring(1);
                String AN = "" + (Integer.parseInt(kode) + 1);
                String Nol = "";
                
                if(AN.length()==1){
                    Nol = "00";
                }
                else if (AN.length()==2){
                    Nol = "0";
                }
                else if (AN.length()==3){
                    Nol = "";
                }
                
                txtIdkue.setText("K" + Nol + AN);
            }else{
               txtIdkue.setText("K001"); 
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpanData();
        AutoId();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        BersihIsian();
        AutoId();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        frmMenu menu = new frmMenu();
        dispose();
        menu.show();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(txtIdkue.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan ID Kue");
        }
        else{
            try{
                objKue.AksesData();
                objKue.Idkue = txtIdkue.getText();
                objKue.Namakue = txtNamakue.getText();
                objKue.Harga = txtHarga.getText();
                
                objKue.Edit();
                objKue.res.executeUpdate(objKue.sql);
                objKue.conn.close();
                BersihIsian();
                IsiTabel();
                AutoId();
                JOptionPane.showMessageDialog(null, "Data Kue Dengan ID " + objKue.Idkue + " Berhasil Diupdate");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Proses penyimpanan gagal/koneksi gagal");
                
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            objKue.AksesData();
            objKue.Idkue = txtIdkue.getText();
            objKue.Hapus();
            objKue.res.executeUpdate(objKue.sql);
            objKue.conn.close();
            IsiTabel();
            BersihIsian();
            AutoId();
            JOptionPane.showMessageDialog(null, "Data Kue Dengan ID "+ objKue.Idkue + " Telah Dihapus");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Proses penghapusan gagal/koneksi gagal");
            
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIdkueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdkueKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            if((txtIdkue.getText().length() < 8)||(txtIdkue.getText().isEmpty())){
                JOptionPane.showMessageDialog(this, "Panjang ID kue harus 4 digit", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                txtIdkue.requestFocus();
            }else{
                txtNamakue.requestFocus();
            }
        }  
    }//GEN-LAST:event_txtIdkueKeyPressed

    private void txtNamakueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamakueKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtNamakue.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nama kue masih kosong", "informasi", JOptionPane.INFORMATION_MESSAGE);
                txtNamakue.requestFocus();
            }else{
                txtHarga.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNamakueKeyPressed

    private void txtHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtHarga.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Harga masih kosong", "informasi", JOptionPane.INFORMATION_MESSAGE);
                txtHarga.requestFocus();
            }else{
                txtHarga.requestFocus();
            }
        }
    }//GEN-LAST:event_txtHargaKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension posisi=Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width-this.getWidth())/2;
        int y = (posisi.height-this.getHeight())/2;
        this.setLocation(x,y);
    }//GEN-LAST:event_formWindowActivated

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int baris = jTable.getSelectedRow();
        
        String kolom1 = jTable.getValueAt(baris, 0).toString();
        String kolom2 = jTable.getValueAt(baris, 1).toString();
        String kolom3 = jTable.getValueAt(baris, 2).toString();
        
        txtIdkue.setText(kolom1);
        txtNamakue.setText(kolom2);
        txtHarga.setText(kolom3);
    }//GEN-LAST:event_jTableMouseClicked

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
        frmUser user = new frmUser();
        dispose();
        user.show();
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuKueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKueActionPerformed
        // TODO add your handling code here:
        frmKue kue = new frmKue();
        dispose();
        kue.show();
    }//GEN-LAST:event_menuKueActionPerformed

    private void menuPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembeliActionPerformed
        // TODO add your handling code here:
        frmPembeli pembeli = new frmPembeli();
        dispose();
        pembeli.show();
    }//GEN-LAST:event_menuPembeliActionPerformed

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed
        // TODO add your handling code here:
        frmTransaksi transaksi = new frmTransaksi();
        dispose();
        transaksi.show();
    }//GEN-LAST:event_menuTransaksiActionPerformed

    private void menuCetakReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCetakReportActionPerformed
        // TODO add your handling code here:
        frmCetakReport report = new frmCetakReport();
        dispose();
        report.show();
    }//GEN-LAST:event_menuCetakReportActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sampai Jumpa, Semoga Hari Anda Menyenangkan :)");
        frmLogin login = new frmLogin();
        dispose();
        login.show();
    }//GEN-LAST:event_menuLogoutActionPerformed
    
    public void BersihIsian(){
        txtIdkue.setText("");
        txtNamakue.setText("");
        txtHarga.setText("");
    }
    
    public void AturKolom(){
        jTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = jTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(160);
        column = jTable.getColumnModel().getColumn(1);
        column.setPreferredWidth(160);
        column = jTable.getColumnModel().getColumn(2);
        column.setPreferredWidth(160);
    }
    
    public void IsiTabel(){
        DefaultTableModel tabelkue = new DefaultTableModel();
        
        tabelkue.addColumn("ID Kue");
        tabelkue.addColumn("Nama Kue");
        tabelkue.addColumn("Harga");
        try{
            objKue.AksesData();
            objKue.TampilData();
            
            Statement stat1 = objKue.conn.createStatement();
            ResultSet res1 = stat1.executeQuery(objKue.sql);
            while (res1.next()){
                tabelkue.addRow(new Object[]{res1.getString(1), res1.getString(2), res1.getString(3)});
            }
            jTable.setModel(tabelkue);
            AturKolom();
        }catch (Exception e){
        }
    }
    
    public void SimpanData(){
        if(txtIdkue.getText().equals("")||txtNamakue.getText().equals("")||txtHarga.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Semua Data Harus Diisi!!!");
        }
        else{
            try{
                objKue.AksesData();
                objKue.Idkue = txtIdkue.getText();
                objKue.Namakue = txtNamakue.getText();
                objKue.Harga = txtHarga.getText();
                
                objKue.Simpan();
                
                objKue.res.executeUpdate(objKue.sql);
                objKue.conn.close();
                BersihIsian();
                IsiTabel();
                JOptionPane.showMessageDialog(null, "Data Kue Dengan ID " + objKue.Idkue + " Berhasil Disimpan");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Proses penyimpanan gagal/koneksi gagal");
                System.out.println(e.getMessage());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JMenuItem menuCetakReport;
    private javax.swing.JMenuItem menuKue;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPembeli;
    private javax.swing.JMenuItem menuTransaksi;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdkue;
    private javax.swing.JTextField txtNamakue;
    // End of variables declaration//GEN-END:variables
}